name: Ason
title: Ason | A blog for development
description: Founder of GDP Studio, Inc. who code and films.
tags:
  - development
  - news
  - management
  - operation
  - tips
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: ason@certifie.io
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id